window.KifunBuyingData = {
  "updated": "2026-09-25",
  "decision": "ซื้อเพียง 1 ตัว รวมไม่เกิน 1kg • ต้องเพิ่มรสจาก Ureshino ที่คุณชิมเป็นถั่วอบ/ถั่วต้ม • เพดาน 13 บาท/g • ไม่บังคับ seaweed",
  "rows": [
    {
      "vendor": "PEACE mini",
      "name": "Matcha Prime",
      "kg": 6750,
      "notes": "House blend · High-firing",
      "source": "mini-prime",
      "pack": "1kg 6,750 บาท",
      "evidence": "ชิมแล้ว: ชอบมาก",
      "status": "แพ็ก 1kg ขึ้น Sold out ในภาพที่ส่ง",
      "rank": 15,
      "reason": "คุณชอบมาก แต่ High-firing เพียงอย่างเดียวไม่ยืนยันว่าไม่ซ้ำ Ureshino; เก็บเป็นตัวเทียบรสที่ชอบ",
      "fit": "ชอบจริง / รอยืนยันความต่าง"
    },
    {
      "vendor": "OSHA OCHA",
      "name": "Fuyu no Kaze",
      "kg": 6900,
      "notes": "Ceremonial ตามข้อมูลผู้ใช้",
      "source": "user",
      "pack": "ผู้ใช้แจ้ง 6,900 บาท • รอยืนยันว่าเป็น 1kg",
      "evidence": "ชิมแล้ว: อร่อยมาก",
      "status": "ต้องยืนยันขนาดแพ็กและสต็อก",
      "rank": 3,
      "reason": "คุณชิมแล้วชอบมาก • รอยืนยันแพ็ก 6,900 บาทและบันทึกโน้ตเทียบ Ureshino ก่อนตัดสินใจ",
      "fit": "ชอบจริง / รอยืนยันความต่าง"
    },
    {
      "vendor": "NOKO",
      "name": "NOKO",
      "kg": 6000,
      "notes": "รสชาติใช้ประสบการณ์ล็อตเดิมของร้าน; ให้ยืนยันรุ่นที่เสนอราคา",
      "source": "user",
      "pack": "500g 3,000 บาท × 2 = 1kg 6,000 บาท",
      "evidence": "ร้านเคยใช้",
      "status": "ต้องยืนยันรุ่น/ล็อตและสต็อก",
      "rank": 20,
      "reason": "เก็บตัวซื้อซ้ำตามที่คุณเสนอ 500g × 2 = 6,000 บาท แต่ยังไม่ผ่านเงื่อนไขยืนยันความต่างของรส",
      "fit": "สำรอง / ข้อมูลรสไม่พอ"
    },
    {
      "vendor": "PEACE mini",
      "name": "Matcha Plus",
      "kg": 4550,
      "notes": "House blend · High-firing",
      "source": "mini-plus",
      "pack": "1kg 4,550 บาท",
      "evidence": "ชิมแล้ว: อร่อย",
      "status": "แพ็ก 1kg ขึ้น Sold out ในภาพที่ส่ง",
      "rank": 16,
      "reason": "ชิมแล้วชอบและประหยัด แต่ยังไม่มีโน้ตเทียบ Ureshino; แพ็กกิโลในภาพหมด",
      "fit": "ชอบจริง / รอยืนยันความต่าง"
    },
    {
      "vendor": "OSHA OCHA",
      "name": "Kagoshima P01",
      "kg": 5270,
      "notes": "Dense body · rice milk · floral nuts · avocado · mango sticky rice",
      "source": "canva",
      "pack": "1kg 5,270 บาท",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": 1,
      "reason": "อันดับ 1 ตามที่คุณเลือก • rice milk / floral / avocado / mango sticky rice เพิ่มมิติจาก Ureshino ถั่วอบ-ถั่วต้ม; ยังมีโน้ตถั่วร่วมอยู่",
      "fit": "น่าสนใจตามโน้ต"
    },
    {
      "vendor": "OSHA OCHA",
      "name": "Yame Saemidori",
      "kg": 6990,
      "notes": "Chocolate · cream · nutty · avocado · hint of ocean",
      "source": "canva",
      "pack": "1kg 6,990 บาท",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": 9,
      "reason": "Chocolate / cream / avocado / hint of ocean เพิ่มมิติ แม้ยังมี nutty",
      "fit": "ต่างบางส่วน"
    },
    {
      "vendor": "OSHA OCHA",
      "name": "Sanji",
      "kg": 6550,
      "notes": "Roasted nuts · ocean",
      "source": "canva",
      "pack": "1kg 6,550 บาท",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": "คั่วถั่วและมีมิติอูมามิ ต้นทุนยังไม่สูง"
    },
    {
      "vendor": "Sukito",
      "name": "Cafe Latte",
      "kg": 7900,
      "notes": "Blend · cafe/latte grade; ใบราคาใหม่ไม่ได้ระบุ tasting notes",
      "source": "sukito",
      "pack": "500g 4,500 / 1kg 7,900 / tester 10g 150",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": "ตัวราคาถึงได้ของแบรนด์ที่คุณชอบ แต่ยังสรุปไม่ได้ว่าจะชอบเท่า Kagoshima 03"
    },
    {
      "vendor": "WARDEN",
      "name": "UJI No.6",
      "kg": 9450,
      "notes": "Creamy · seaweed ในนม; ชงใสอาจขม",
      "source": "warden",
      "pack": "500g 5,850 / 1kg 9,450 • รวม VAT",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": 5,
      "reason": "Creamy seaweed ในนม เป็นแนวเพิ่มรสที่ต่างจากฐานถั่วเดิม; ชงใสอาจขม",
      "fit": "น่าสนใจตามโน้ต"
    },
    {
      "vendor": "CHaEN",
      "name": "Yame for Cafe",
      "kg": 6000,
      "notes": "Blend · 1st + 2nd harvest · walnut · almond",
      "source": "chaen-culinary",
      "pack": "100g 700 / 1kg 6,000",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": "โทนถั่ว ราคาใกล้ NOKO มีแพ็ก 100g ไว้ทดสอบ"
    },
    {
      "vendor": "OSHA OCHA",
      "name": "Yame Yabukita",
      "kg": 5800,
      "notes": "Rich roasted nuts",
      "source": "canva",
      "pack": "1kg 5,800 บาท",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": "คั่วถั่วตรงทิศทางที่น่าสนใจ และต้นทุนต่ำ"
    },
    {
      "vendor": "Ryn",
      "name": "Organic Saemidori",
      "kg": 10000,
      "notes": "Floral mochi · snow peas",
      "source": "canva",
      "pack": "100g 1,350 / 500g 5,500 / 1kg 10,000",
      "evidence": "ยังไม่ได้ชิม",
      "status": "ราคา Canva 1kg 10,000 บาท; ร้าน Shopee มีแพ็ก 500g/1kg ราคาเริ่ม 6,000 ซึ่งยังจับคู่ขนาดไม่ได้ ต้องขอราคา 1kg ใหม่",
      "rank": 2,
      "reason": "Floral mochi น่าจะเพิ่มกลิ่นหอมหวาน; snow peas อาจซ้ำถั่วต้มบางส่วน ต้องชิมเทียบและยืนยันราคากิโลใหม่",
      "taste_url": "https://shopee.co.th/ryntea",
      "fit": "น่าสนใจตามโน้ต"
    },
    {
      "vendor": "WARDEN",
      "name": "UJI No.5",
      "kg": 10650,
      "notes": "Creamy · macadamia ในนม; mild seaweed เมื่อชงใส",
      "source": "warden",
      "pack": "500g 6,900 / 1kg 10,650 • รวม VAT",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": 7,
      "reason": "มี mild seaweed และครีมมี่ แต่ macadamia ยังซ้ำกลุ่มถั่วบางมิติ",
      "fit": "ต่างบางส่วน"
    },
    {
      "vendor": "CHaEN",
      "name": "Yame Toku",
      "kg": 11000,
      "notes": "Yabukita · 1st harvest · almond · creamy",
      "source": "chaen-ceremonial",
      "pack": "100g 1,300 / 1kg 11,000",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": "อัลมอนด์ครีมมี่ น่าชิมก่อนซื้อกิโลที่แพงขึ้น"
    },
    {
      "vendor": "CHaEN",
      "name": "Yame Classic",
      "kg": 11500,
      "notes": "Yabukita + Saemidori · 1st harvest · nutty",
      "source": "chaen-ceremonial",
      "pack": "30g 650 / 100g 1,350 / 1kg 11,500",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": "โทนถั่วในงบสูงสุด แต่ข้อมูลความชอบจริงยังน้อยกว่าตัวอันดับต้น"
    },
    {
      "vendor": "Sukito",
      "name": "Smoky",
      "kg": 16000,
      "notes": "Roasted peanut · coffee bean · cocoa nib · smoky",
      "source": "sukito",
      "pack": "500g 8,500 / tester 10g 234 / 1kg 16,000",
      "evidence": "ยังไม่ได้ชิม",
      "status": "เกินเพดาน 13 บาท/g • สอบถามสต็อก",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Sukito",
      "name": "Roasty",
      "kg": 16000,
      "notes": "Roasted peanut · salty cream cheese · white chocolate",
      "source": "sukito",
      "pack": "500g 8,500 / tester 10g 234 / 1kg 16,000",
      "evidence": "ยังไม่ได้ชิม",
      "status": "เกินเพดาน 13 บาท/g • สอบถามสต็อก",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Sukito",
      "name": "Ob-oon",
      "kg": 17500,
      "notes": "Almond · buttery · milk honey · cereal · floral",
      "source": "sukito",
      "pack": "500g 9,500 / tester 10g 247 / 1kg 17,500",
      "evidence": "ยังไม่ได้ชิม",
      "status": "เกินเพดาน 13 บาท/g • สอบถามสต็อก",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Sukito",
      "name": "Arigato",
      "kg": 17500,
      "notes": "Broad bean · slightly pistachio · roasty · gentle floral",
      "source": "sukito",
      "pack": "500g 9,500 / tester 10g 247 / 1kg 17,500",
      "evidence": "ผู้ใช้เชื่อรีวิวว่าดีมาก; ยังไม่ได้ชิม",
      "status": "เกินเพดาน 13 บาท/g • สอบถามสต็อก",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Sukito",
      "name": "Pure Dairy",
      "kg": 15500,
      "notes": "Peanut · hint of floral · white chocolate",
      "source": "sukito",
      "pack": "500g 8,300 / tester 10g 234 / 1kg 15,500",
      "evidence": "ยังไม่ได้ชิม",
      "status": "เกินเพดาน 13 บาท/g • สอบถามสต็อก",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Sukito",
      "name": "Tsuyuhikari Yame",
      "kg": 15500,
      "notes": "Velvety · green peas · white chocolate · roasty",
      "source": "sukito",
      "pack": "500g 8,300 / tester 10g 234 / 1kg 15,500",
      "evidence": "ยังไม่ได้ชิม",
      "status": "เกินเพดาน 13 บาท/g • สอบถามสต็อก",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Sukito",
      "name": "Kagoshima 03",
      "kg": 13500,
      "notes": "Blend · Kagoshima; ใบราคาไม่ได้ระบุโน้ต",
      "source": "sukito",
      "pack": "500g 7,000 / tester 10g 172 / 1kg 13,500",
      "evidence": "ชิมแล้ว: อร่อยมาก",
      "status": "เกินเพดาน 13 บาท/g • สอบถามสต็อก",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Sukito",
      "name": "Funky",
      "kg": 13500,
      "notes": "Kirari 31 · Kagoshima",
      "source": "sukito",
      "pack": "500g 7,000 / tester 10g 172 / 1kg 13,500",
      "evidence": "ยังไม่ได้ชิม",
      "status": "เกินเพดาน 13 บาท/g • สอบถามสต็อก",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Sukito",
      "name": "Choki Choki",
      "kg": 13500,
      "notes": "Yabukita · Fukuoka",
      "source": "sukito",
      "pack": "500g 7,500 / tester 10g 172 / 1kg 13,500",
      "evidence": "ยังไม่ได้ชิม",
      "status": "เกินเพดาน 13 บาท/g • สอบถามสต็อก",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Sukito",
      "name": "Kurumi / กระรอก",
      "kg": null,
      "notes": "ชอบมาก แต่ไม่มีราคาส่งตามข้อมูลผู้ใช้",
      "source": "user",
      "pack": "ทุนเดิมใน Supabase: 30g 470 บาท; ไม่ใช่ใบเสนอราคาใหม่",
      "evidence": "ชิมแล้ว: อร่อยมาก",
      "status": "ไม่มีราคาส่ง",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "CHaEN",
      "name": "DAI",
      "kg": 4800,
      "notes": "2nd harvest · cookie · wheatgrass",
      "source": "chaen-catalog",
      "pack": "100g 580 / 500g 2,500 / 1kg 4,800",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": 13,
      "reason": "Cookie / wheatgrass เปลี่ยนไปทางคุกกี้และเขียว; ยังไม่มีผลชิมว่าชอบหรือเหมาะสูตรร้าน",
      "fit": "น่าสนใจตามโน้ต"
    },
    {
      "vendor": "CHaEN",
      "name": "DAI HFR",
      "kg": 5000,
      "notes": "2nd harvest · barley · grain",
      "source": "chaen-catalog",
      "pack": "100g 600 / 500g 2,600 / 1kg 5,000",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": 14,
      "reason": "Barley / grain เพิ่มแนวธัญพืช; อาจยังให้ความอบคล้ายฐานเดิม ควรเทียบแบบปิดชื่อ",
      "fit": "ต่างบางส่วน"
    },
    {
      "vendor": "CHaEN",
      "name": "Yame Begin",
      "kg": 8800,
      "notes": "1st harvest · creamy · slightly bitter",
      "source": "chaen-catalog",
      "pack": "30g 600 / 100g 1,100 / 1kg 8,800",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "CHaEN",
      "name": "Yame no Mori",
      "kg": 13000,
      "notes": "Macadamia · salted egg yolk pastry",
      "source": "chaen-catalog",
      "pack": "100g 1,500 / 1kg 13,000",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "CHaEN",
      "name": "Yame Kyu",
      "kg": 13500,
      "notes": "Chestnuts · cashew nut · light roasted",
      "source": "chaen-catalog",
      "pack": "30g 700 / 100g 1,550 / 1kg 13,500",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "CHaEN",
      "name": "Yame Tsuyuhikari",
      "kg": 14000,
      "notes": "Peanut · pistachio · floral",
      "source": "chaen-catalog",
      "pack": "30g 750 / 100g 1,600 / 1kg 14,000",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "CHaEN",
      "name": "Yame no Wabi",
      "kg": 14000,
      "notes": "Medium roasted · pistachio",
      "source": "chaen-catalog",
      "pack": "100g 1,600 / 1kg 14,000",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "CHaEN",
      "name": "Yame Majesty",
      "kg": 15000,
      "notes": "Umami · creamy · dark chocolate",
      "source": "chaen-catalog",
      "pack": "30g 800 / 100g 1,700 / 1kg 15,000",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "CHaEN",
      "name": "Chiran Kirari31",
      "kg": 11500,
      "notes": "Corn · herb",
      "source": "chaen-catalog",
      "pack": "30g 650 / 100g 1,350 / 1kg 11,500",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": 6,
      "reason": "Corn / herb เป็นอีกทางจากถั่วอบ ไม่จำเป็นต้องเน้นสาหร่าย",
      "fit": "น่าสนใจตามโน้ต"
    },
    {
      "vendor": "CHaEN",
      "name": "Satsuma no Hana",
      "kg": 19900,
      "notes": "Umami · floral · potato · butter",
      "source": "chaen-catalog",
      "pack": "30g 890 / 100g 2,200 / 1kg 19,900",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "CHaEN",
      "name": "Hikaru",
      "kg": 19500,
      "notes": "Umami · macadamia · vanilla · light seaweed",
      "source": "chaen-catalog",
      "pack": "20g 650 / 100g 2,100 / 1kg 19,500",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "CHaEN",
      "name": "Uji Blend",
      "kg": 16500,
      "notes": "Umami · seaweed",
      "source": "chaen-catalog",
      "pack": "30g 800 / 100g 1,850 / 1kg 16,500",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "CHaEN",
      "name": "Kyoto Nutty",
      "kg": 24000,
      "notes": "Nutty · toast · mellow · hint of roasted",
      "source": "chaen-catalog",
      "pack": "20g 880 / 100g 2,990 / 1kg 24,000",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "CHaEN",
      "name": "Roasted Kirari31",
      "kg": 11500,
      "notes": "Roasted peanut · rice caramel crispy · cacao",
      "source": "chaen-catalog",
      "pack": "30g 650 / 100g 1,350 / 1kg 11,500",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "CHaEN",
      "name": "Yame no Fumi",
      "kg": 12500,
      "notes": "Roasted nutty · black sesame · toast",
      "source": "chaen-catalog",
      "pack": "30g 650 / 100g 1,450 / 1kg 12,500",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "CHaEN",
      "name": "Uji Samidori",
      "kg": null,
      "notes": "Umami · rich · seaweed",
      "source": "chaen-catalog",
      "pack": "20g 1,250 / 100g 5,500",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "CHaEN",
      "name": "Uji Hikari",
      "kg": null,
      "notes": "Umami · fresh · avocado",
      "source": "chaen-catalog",
      "pack": "20g 1,250",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "CHaEN",
      "name": "Baiko",
      "kg": null,
      "notes": "Roasted peanut · medium smoky · cereal",
      "source": "chaen-catalog",
      "pack": "30g 850",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "WARDEN",
      "name": "UJI No.7",
      "kg": 7800,
      "notes": "Creamy · seaweed ในนม; แนะนำเติมหวาน; ชงใสขมไม่แนะนำ",
      "source": "warden",
      "pack": "500g 5,300 / 1kg 7,800 • รวม VAT",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": 10,
      "reason": "Creamy seaweed ในนม ราคาย่อมกว่า No.5/6; supplier แนะนำหวานและไม่แนะนำชงใส",
      "fit": "น่าสนใจตามโน้ต"
    },
    {
      "vendor": "OSHA OCHA",
      "name": "Sancho",
      "kg": 10500,
      "notes": "Smooth roasted nuts · peeled mung bean · savory fish snack · hint of yuzu",
      "source": "canva",
      "pack": "500g 6,250 / 10500 บาท/kg",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": 11,
      "reason": "มี savory fish snack และ hint of yuzu แต่ถั่วคั่วกับถั่วเขียวปอกเปลือกยังเสี่ยงทับ Ureshino",
      "fit": "ต่างบางส่วน"
    },
    {
      "vendor": "OSHA OCHA",
      "name": "Yame Okumidori",
      "kg": 12500,
      "notes": "Smooth roasted nuts · pear · buttery bread",
      "source": "canva",
      "pack": "500g 7,900 / 12500 บาท/kg",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": 12,
      "reason": "Pear / buttery bread เพิ่มมิติ แต่มี roasted nuts; ราคาใกล้เพดาน ต้องชิมก่อนกิโล",
      "fit": "ต่างบางส่วน"
    },
    {
      "vendor": "OSHA OCHA",
      "name": "Yame C00",
      "kg": 11490,
      "notes": "Smoky · roasted nuts/rice · pistachio · fruity",
      "source": "canva",
      "pack": "tester 30g 700 / 11490 บาท/kg",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "OSHA OCHA",
      "name": "Gyokuro Asanoka",
      "kg": 11090,
      "notes": "Nutty · steamed white fish · fruity",
      "source": "canva",
      "pack": " / 11090 บาท/kg",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "OSHA OCHA",
      "name": "C02",
      "kg": null,
      "notes": "Coming soon",
      "source": "canva",
      "pack": "ยังไม่มีราคาที่อ่านยืนยันได้",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Midori Shinsei",
      "name": "KU03",
      "kg": 7704.0,
      "notes": "ใช้ชื่อรหัสตาม supplier; ยังไม่สรุป tasting notes จากจุดคะแนน",
      "source": "canva",
      "pack": "1kg 7,200 ก่อน VAT + 7% = 7,704.00",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Midori Shinsei",
      "name": "KU04",
      "kg": 6741.0,
      "notes": "ใช้ชื่อรหัสตาม supplier; ยังไม่สรุป tasting notes จากจุดคะแนน",
      "source": "canva",
      "pack": "1kg 6,300 ก่อน VAT + 7% = 6,741.00",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Midori Shinsei",
      "name": "MI02",
      "kg": 7704.0,
      "notes": "ใช้ชื่อรหัสตาม supplier; ยังไม่สรุป tasting notes จากจุดคะแนน",
      "source": "canva",
      "pack": "1kg 7,200 ก่อน VAT + 7% = 7,704.00",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Midori Shinsei",
      "name": "MI01",
      "kg": 12519.0,
      "notes": "ใช้ชื่อรหัสตาม supplier; ยังไม่สรุป tasting notes จากจุดคะแนน",
      "source": "canva",
      "pack": "1kg 11,700 ก่อน VAT + 7% = 12,519.00",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Midori Shinsei",
      "name": "SM02",
      "kg": 11556.0,
      "notes": "ใช้ชื่อรหัสตาม supplier; ยังไม่สรุป tasting notes จากจุดคะแนน",
      "source": "canva",
      "pack": "1kg 10,800 ก่อน VAT + 7% = 11,556.00",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Midori Shinsei",
      "name": "SM03",
      "kg": 11556.0,
      "notes": "ใช้ชื่อรหัสตาม supplier; ยังไม่สรุป tasting notes จากจุดคะแนน",
      "source": "canva",
      "pack": "1kg 10,800 ก่อน VAT + 7% = 11,556.00",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Midori Shinsei",
      "name": "AN03",
      "kg": 5778.0,
      "notes": "ใช้ชื่อรหัสตาม supplier; ยังไม่สรุป tasting notes จากจุดคะแนน",
      "source": "canva",
      "pack": "1kg 5,400 ก่อน VAT + 7% = 5,778.00",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Midori Shinsei",
      "name": "FY04",
      "kg": 6955.0,
      "notes": "ใช้ชื่อรหัสตาม supplier; ยังไม่สรุป tasting notes จากจุดคะแนน",
      "source": "canva",
      "pack": "1kg 6,500 ก่อน VAT + 7% = 6,955.00",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Midori Shinsei",
      "name": "KS05",
      "kg": 4494.0,
      "notes": "ใช้ชื่อรหัสตาม supplier; ยังไม่สรุป tasting notes จากจุดคะแนน",
      "source": "canva",
      "pack": "1kg 4,200 ก่อน VAT + 7% = 4,494.00",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Midori Shinsei",
      "name": "KS04",
      "kg": 7704.0,
      "notes": "ใช้ชื่อรหัสตาม supplier; ยังไม่สรุป tasting notes จากจุดคะแนน",
      "source": "canva",
      "pack": "1kg 7,200 ก่อน VAT + 7% = 7,704.00",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Midori Shinsei",
      "name": "KC03",
      "kg": 10593.0,
      "notes": "ใช้ชื่อรหัสตาม supplier; ยังไม่สรุป tasting notes จากจุดคะแนน",
      "source": "canva",
      "pack": "1kg 9,900 ก่อน VAT + 7% = 10,593.00",
      "evidence": "ยังไม่ได้ชิม",
      "status": "สอบถามสต็อกก่อนซื้อ",
      "rank": null,
      "reason": ""
    },
    {
      "vendor": "Trial Matcha",
      "name": "Uji Heritage",
      "kg": 21000,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 6,250 / 500g 11,700 / 1kg 21,000 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Uji Ceremonial",
      "kg": 13600,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 4,050 / 500g 7,250 / 1kg 13,600 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Uji Premium upper",
      "kg": 10700,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 3,250 / 500g 5,700 / 1kg 10,700 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": 17,
      "reason": "ราคา 10.70 บาท/g อยู่ในงบ; รอ supplier ยืนยันโน้ตของรุ่น upper ห้ามใช้โน้ต Premium แทน",
      "taste_url": null,
      "fit": "สำรอง / ข้อมูลรสไม่พอ"
    },
    {
      "vendor": "Trial Matcha",
      "name": "Uji Premium",
      "kg": 9800,
      "notes": "Grassy · seaweed · nutty; ขมปลายเล็กน้อย",
      "source": "trial-sep",
      "pack": "250g 2,990 / 500g 5,540 / 1kg 9,800 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": 4,
      "reason": "Grassy / seaweed เพิ่มทางสดชื่นจากถั่วอบ แต่ยังมี nutty; supplier ระบุเหมาะลงนมและน้ำผลไม้",
      "taste_url": "https://shop.line.me/%40trialmatcha/product/1002787071",
      "fit": "น่าสนใจตามโน้ต"
    },
    {
      "vendor": "Trial Matcha",
      "name": "Uji Cafe A",
      "kg": 6800,
      "notes": "Nutty · malty · almond; เสี่ยงซ้ำถั่วอบของ Ureshino",
      "source": "trial-sep",
      "pack": "250g 2,080 / 500g 3,650 / 1kg 6,800 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": "https://shop.line.me/%40trialmatcha/product/1001508944"
    },
    {
      "vendor": "Trial Matcha",
      "name": "Uji Culinary",
      "kg": 6800,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 2,080 / 500g 3,650 / 1kg 6,800 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Yame Gyokuro",
      "kg": 8700,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 2,610 / 500g 4,880 / 1kg 8,700 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Yame White Tea Powder",
      "kg": 10500,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 3,150 / 500g 5,900 / 1kg 10,500 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Hoshinomura Gyokuro",
      "kg": 11100,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 3,220 / 500g 6,230 / 1kg 11,100 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Hoshinomura Premium",
      "kg": 9000,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 2,700 / 500g 5,050 / 1kg 9,000 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Nishio Supreme",
      "kg": 68000,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 20,400 / 500g 38,200 / 1kg 68,000 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Nishio Heritage",
      "kg": 28000,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 8,400 / 500g 15,700 / 1kg 28,000 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Nishio Ceremonial",
      "kg": 21000,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 6,250 / 500g 11,700 / 1kg 21,000 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Nishio Chocolate",
      "kg": 16000,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 4,760 / 500g 8,910 / 1kg 16,000 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Nishio Premium",
      "kg": 13000,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 3,900 / 500g 7,200 / 1kg 13,000 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Nishio Cafe",
      "kg": 11000,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 3,300 / 500g 6,100 / 1kg 11,000 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Nishio for latte",
      "kg": 8900,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 2,680 / 500g 4,990 / 1kg 8,900 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Nishio all purpose",
      "kg": 6100,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 1,830 / 500g 3,450 / 1kg 6,100 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Organic Nishio heritage",
      "kg": 24000,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 7,200 / 500g 13,500 / 1kg 24,000 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Organic Nishio ceremonial",
      "kg": 14000,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 4,200 / 500g 7,850 / 1kg 14,000 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Organic Nishio cafe",
      "kg": 4700,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 1,420 / 500g 2,650 / 1kg 4,700 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": 19,
      "reason": "ราคา 4.70 บาท/g คุ้มพอให้ตรวจต่อ แต่ไม่มีหลักฐานว่ารสต่างจาก Ureshino",
      "taste_url": null,
      "fit": "สำรอง / ข้อมูลรสไม่พอ"
    },
    {
      "vendor": "Trial Matcha",
      "name": "Ise heritage",
      "kg": 20500,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 6,150 / 500g 11,500 / 1kg 20,500 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Ise ceremonial",
      "kg": 18500,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 5,550 / 500g 10,380 / 1kg 18,500 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Ise premium",
      "kg": 14500,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 4,350 / 500g 8,100 / 1kg 14,500 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Ise cafe",
      "kg": 9200,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 2,760 / 500g 5,160 / 1kg 9,200 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Ise for latte",
      "kg": 6500,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 1,950 / 500g 3,660 / 1kg 6,500 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Kagoshima Ceremonial",
      "kg": 9200,
      "notes": "Edamame · spinach · floral; มีถั่วแระต้มจึงอาจซ้ำบางมิติ",
      "source": "trial-sep",
      "pack": "250g 2,760 / 500g 5,160 / 1kg 9,200 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": 8,
      "reason": "Floral / spinach เพิ่มแนวสด แต่มีถั่วแระต้มร่วมด้วย จึงต้องชิมว่าต่างพอหรือไม่",
      "taste_url": "https://shop.line.me/%40trialmatcha/product/1007431242",
      "fit": "ต่างบางส่วน"
    },
    {
      "vendor": "Trial Matcha",
      "name": "Shizuoka Premium",
      "kg": 9800,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 3,000 / 500g 5,550 / 1kg 9,800 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": 18,
      "reason": "ราคา 9.80 บาท/g; ขอ tester และโน้ตก่อน ไม่สรุปรสจากชื่อแหล่งปลูก",
      "taste_url": null,
      "fit": "สำรอง / ข้อมูลรสไม่พอ"
    },
    {
      "vendor": "Trial Matcha",
      "name": "Samidori",
      "kg": 25000,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 7,500 / 500g 14,000 / 1kg 25,000 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Kanayamidori (Pesticide-Free)",
      "kg": 19500,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 5,850 / 500g 10,990 / 1kg 19,500 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Okuyutaka (Pesticide-Free)",
      "kg": 18000,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 5,400 / 500g 10,100 / 1kg 18,000 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Uji Okumidori",
      "kg": 8500,
      "notes": "Edamame · walnut · white chocolate; โทนถั่วอาจซ้ำฐานเดิม",
      "source": "trial-sep",
      "pack": "250g 2,950 / 500g 5,480 / 1kg 8,500 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": "https://shop.line.me/%40trialmatcha/product/1004970377"
    },
    {
      "vendor": "Trial Matcha",
      "name": "Everyday Nutty (Premium Grade)",
      "kg": 13000,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 3,900 / 500g 7,200 / 1kg 13,000 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Dark Hojicha powder",
      "kg": 4500,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 1,350 / 500g 2,520 / 1kg 4,500 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Rich Hojicha powder",
      "kg": 5500,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 1,650 / 500g 3,080 / 1kg 5,500 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Kagoshima Hojicha",
      "kg": 3500,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 1,050 / 500g 1,960 / 1kg 3,500 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    },
    {
      "vendor": "Trial Matcha",
      "name": "Genmaicha powder",
      "kg": 4500,
      "notes": "ยังไม่ยืนยัน tasting notes ของรุ่นนี้",
      "source": "trial-sep",
      "pack": "250g 1,350 / 500g 2,520 / 1kg 4,500 บาท",
      "evidence": "ยังไม่ได้ชิม • ชื่อเสียงแบรนด์ไม่ใช่ผลชิมรายรุ่น",
      "status": "ใบราคามีผลถึง 30 ก.ย. 2026; สีแดงไม่มีคำอธิบาย จึงไม่ใช้สรุปว่าหมด",
      "rank": null,
      "reason": "",
      "taste_url": null
    }
  ],
  "revision": "top20-p01-desktop-20260925",
  "primary_workspace": "C:\\Users\\ASUS\\Desktop\\Happihause matcha",
  "ranking_note": "P01 อันดับ 1 ตามผู้ใช้; ลำดับอื่นเป็นข้อเสนอจากโน้ต ไม่ใช่ผลชิมยืนยัน; ตัวสำรองไม่ผ่านการยืนยันความต่าง",
  "excluded_from_ranking": [
    "Rinya Ureshino Premium Blend #2"
  ],
  "ranking_size": 20
};