/* Procurement references: never write quotations into purchased inventory. */
window.KifunBuying = (() => {
  const e = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money = n => n == null ? '—' : n.toLocaleString('th-TH',{maximumFractionDigits:2});
  const sources = {canva:['Canva supplier','https://canva.link/hlyl9oauflejd3q'],user:['ข้อมูลผู้ใช้ · 25 ก.ย. 2026',null],warden:['WARDEN · PDF ก.ย. 2026','supplier-sources/warden.pdf']};
  ['mini-prime','mini-plus','sukito','chaen-culinary','chaen-ceremonial','chaen-catalog','trial-sep'].forEach(k => sources[k]=['ภาพราคาที่ผู้ใช้ส่ง','supplier-sources/'+k+'.png']);
  function source(r) { const [label,url]=sources[r.source] || ['ข้อมูลเดิม',null]; return (url ? `<a href="${e(url)}" target="_blank" rel="noopener">${e(label)} ↗</a>` : e(label)) + (r.taste_url ? `<br><a href="${e(r.taste_url)}" target="_blank" rel="noopener">รายละเอียดจากร้าน ↗</a>` : ''); }
  function render(legacy) {
    const d=window.KifunBuyingData, ranked=d.rows.filter(r=>r.rank).sort((a,b)=>a.rank-b.rank);
    const cards=ranked.map(r=>`<article class="buy-card"><div class="buy-rank">${r.rank}</div><div><small>${e(r.vendor)} · ${e(r.evidence)}</small><p class="buy-status">${e(r.fit)}</p><h3>${e(r.name)}</h3><p>${e(r.reason)}</p><p class="buy-note">${e(r.notes)}</p><p><strong>${e(r.pack)}</strong></p><p class="buy-status">${e(r.status)}</p><small>${source(r)}</small></div><div class="buy-cost"><b>${money(r.kg/1000)}</b> บาท/g${r.name==='Fuyu no Kaze'?'*':''}<small>ผง 4g: ${money(r.kg/250)} บาท<br>ผง 5g: ${money(r.kg/200)} บาท</small></div></article>`).join('');
    return `<section class="buy-board"><div class="buy-hero"><small>BUYING BOARD · อัปเดต ${d.updated}</small><h2>20 ตัวเลือก · ซื้อเพียงตัวเดียว</h2><p>${e(d.decision)}</p><p>อันดับเป็นข้อเสนอเพื่อช่วยตัดสินใจ ให้น้ำหนักความต่างจากถั่วอบ/ถั่วต้มของ Ureshino ร่วมกับความชอบจริงและราคา; ตัวที่ระบุ “สำรอง” ยังไม่ผ่านการยืนยันความต่างของรส จึงควรขอข้อมูลหรือชิมก่อนซื้อกิโล; ไม่มีหลักฐานพอจะรับรองว่าทั้ง 20 ตัวรสไม่ซ้ำ สถานะของยังต้องสอบถาม supplier</p><div class="buy-summary"><b>อันดับ 1: Kagoshima P01</b> ตามที่คุณเลือก · 5,270 บาท/kg · 5.27 บาท/g<br><b>Fuyu no Kaze</b> ชอบจริง · รอยืนยัน 6,900 บาทต่อ 1kg และความต่างจากฐานเดิม<br><b>Ryn Organic Saemidori</b> Floral mochi / snow peas · ขอราคา kg ใหม่ก่อนซื้อ<br><b>Trial Uji Premium</b> Grassy / seaweed / nutty · 9,800 บาท/kg<br><b>ถั่วซ้ำควรลดอันดับ:</b> Trial Uji Cafe A, Uji Okumidori และกลุ่ม nutty ล้วน</div><p class="buy-note">ราคาเป็นข้อมูลจัดซื้อใหม่ ไม่แก้ต้นทุนล็อตที่มีอยู่ใน Supabase • ผง 4g/5g ยังไม่รวมวัตถุดิบอื่น แพ็กเกจ และค่าช่องทางขาย • ไม่รวมค่าส่ง; VAT ระบุเฉพาะที่มีหลักฐาน</p></div><div class="buy-grid">${cards}</div><section class="buy-library"><h2>ข้อมูล supplier ที่อัปเดต · ${d.rows.length} รายการ</h2><p>รวมตัวเกินงบ เช่น Kagoshima 03 (13.50 บาท/g), Arigato (17.50 บาท/g) และ Kurumi ที่ไม่มีราคาส่งไว้ให้เทียบด้วย</p><div class="buy-controls"><label>ค้นหาชา / supplier / โน้ต<input id="buy-search" type="search" placeholder="เช่น nutty, Sukito, Uji"></label><label>กรอง<select id="buy-filter"><option value="all">ทั้งหมด</option><option value="rank">Top 20</option><option value="cap">ไม่เกิน 13 บาท/g</option><option value="liked">ชิมแล้วชอบ</option><option value="over">เกินงบ / ไม่มีราคา kg</option></select></label><label>เรียง<select id="buy-sort"><option value="default">ตามรายการ</option><option value="price">ราคาต่ำ → สูง</option><option value="vendor">Supplier</option></select></label></div><p id="buy-count" aria-live="polite"></p><div class="buy-table-wrap"><table class="buy-table"><thead><tr><th>ชา / หลักฐานรสชาติ</th><th>ราคาแพ็ก / บาทต่อ g</th><th>โน้ต / สถานะ</th><th>แหล่งข้อมูล</th></tr></thead><tbody id="buy-rows"></tbody></table></div></section><details class="buy-legacy"><summary>ข้อมูลเก่าจากเว็บ ${legacy.length} รายการ — ยังไม่ได้ตรวจราคาใหม่ทั้งหมด</summary><p>ใช้เป็นประวัติอ้างอิงเท่านั้น หากชื่อซ้ำให้ใช้ราคาในตารางอัปเดตด้านบน; Ureshino ซื้อแล้ว ไม่อยู่ใน Top 20</p><div class="buy-table-wrap"><table class="buy-table"><thead><tr><th>Supplier / ชา</th><th>ราคาเดิมที่บันทึก</th><th>หมายเหตุเดิม</th></tr></thead><tbody>${legacy.map(r=>`<tr><td>${e(r[0])}<br>${e(r[1])}</td><td>${money(r[2])}</td><td>${e(r[3])}</td></tr>`).join('')}</tbody></table></div></details></section>`;
  }
  function update() {
    const target=document.querySelector('#buy-rows'); if(!target)return;
    const q=document.querySelector('#buy-search').value.toLowerCase(), f=document.querySelector('#buy-filter').value, s=document.querySelector('#buy-sort').value;
    let rows=window.KifunBuyingData.rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q)).filter(r=>f==='all'||f==='rank'&&r.rank||f==='cap'&&r.kg!=null&&r.kg<=13000||f==='liked'&&r.evidence.startsWith('ชิมแล้ว')||f==='over'&&(r.kg==null||r.kg>13000));
    if(s==='price')rows.sort((a,b)=>(a.kg??Infinity)-(b.kg??Infinity)); if(s==='vendor')rows.sort((a,b)=>a.vendor.localeCompare(b.vendor));
    target.innerHTML=rows.map(r=>`<tr><td><strong>${e(r.name)}</strong><br>${e(r.vendor)}${r.rank?` · #${r.rank}`:''}<br><small>${e(r.evidence)}</small></td><td>${e(r.pack)}<br><b>${r.kg==null?'ไม่ทราบ':money(r.kg/1000)+' บาท/g'}</b>${r.name==='Fuyu no Kaze'?'<br>*รอยืนยันแพ็ก 1kg':''}</td><td>${e(r.notes)}<br><small>${e(r.status)}</small></td><td>${source(r)}</td></tr>`).join('');
    document.querySelector('#buy-count').textContent=`แสดง ${rows.length} รายการ`;
  }
  document.addEventListener('input',ev=>{if(ev.target.id==='buy-search')update();});
  document.addEventListener('change',ev=>{if(['buy-filter','buy-sort'].includes(ev.target.id))update();});
  return {render,update};
})();
